language: ruby
os: ["linux"]
dist: xenial
rvm:
- 3.1

services:
  - postgresql
  
before_install: gem install bundler

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.travis.yml config/database.yml
  - export PARALLEL_TEST_PROCESSORS=4
  - RAILS_ENV=development bundle exec rake db:create db:migrate

deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: oJDklZylQHKAOVOuZCY5FbkAeOrrEeZx/T1NjeE0G9EQITtxWzZijM7epiOxehZfZbatKUlcfGMeVggu1dqMpQTAa1QpjiXHpv6Rn2qOs9WVBVwj2FvP6Q3CUzfHAqD0n87+qHVyXv93R6AcCC5+d6bw9V2/BWDMe77UoM4jAOALW3N7R7PlYEXSjwKlTX4wOy4IPxGA5UD6pRYlFvzcIBUl1RnoX73c70jRHFPWNG/6Dv/DC0yQ3KxdDDB93ZCBVQ1ozoKG91OcZ1AyzpKzg36ByUNvmPyPHmg6dND2oqnTJyc1s11jscYuVWG5+2SZ7MAhUOhb17swUwk7w2DRpCCaQNNvQi6C7Cc94mcoIb0xDB+oI831Uk8G3esZxyS1UM+JCWoUJTTXGnE+0LBMrx76VhxELRCboz7WLO6NntOaklUI6yNmfrVdRTsaCsIeKYbFZqPC7nBZTf7V+HJp/ohFkDGV7AacLpHtaIZr7jO0nxAJZ5mE6LCc7T5XoHEmEMCFK06thR24iwzSr42/3D41az2oJbSVFfxp+bxxthVjlth4WbKLdWO9ODuENCKhaqYKRvKpOpi8J5E4LabpyyXEK1V068NI+2kleOVhykKtWksniRpUVepv4iL/nXorOGFlP7ecWEZObFYU9+pyVLxM03RwMBUGArQjSY8WoF4=
  app: rails-sti
  on:
    repo: yosefbennywidyo/rails-sti